"""initial schema

Revision ID: b71aefe6477c
Revises: 
Create Date: 2026-09-05 23:13:14.709812
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b71aefe6477c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('beats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('range_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'range_id', name='uq_beats_id_range'),
    sa.UniqueConstraint('range_id', 'name', name='uq_beats_range_name')
    )
    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beats_range_id'), ['range_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('reserve_admin', 'range_user', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('range_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("(role = 'reserve_admin' AND range_id IS NULL) OR (role = 'range_user' AND range_id IS NOT NULL)", name='ck_users_role_range_consistency'),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('in_stock', 'allocated', 'deployed', name='camera_status', native_enum=False, length=32), nullable=False),
    sa.Column('range_id', sa.Integer(), nullable=True),
    sa.Column('beat_id', sa.Integer(), nullable=True),
    sa.Column('site_name', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("\n            (status = 'in_stock'  AND range_id IS NULL AND beat_id IS NULL)\n         OR (status = 'allocated' AND range_id IS NOT NULL)\n         OR (status = 'deployed'  AND range_id IS NOT NULL AND beat_id IS NOT NULL\n             AND site_name IS NOT NULL AND latitude IS NOT NULL AND longitude IS NOT NULL\n             AND contact_name IS NOT NULL AND contact_phone IS NOT NULL)\n            ", name='ck_cameras_status_requirements'),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name='ck_cameras_coordinates_paired'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_cameras_latitude_bounds'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_cameras_longitude_bounds'),
    sa.ForeignKeyConstraint(['beat_id', 'range_id'], ['beats.id', 'beats.range_id'], name='fk_cameras_beat_within_range', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_beat_id'), ['beat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cameras_range_id'), ['range_id'], unique=False)
        batch_op.create_index('ix_cameras_range_status', ['range_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cameras_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cameras_status'), ['status'], unique=False)

    op.create_table('assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('change_type', sa.Enum('registered', 'allocated', 'transferred', 'deployed', 'details_updated', 'returned_to_stock', name='change_type', native_enum=False, length=32), nullable=False),
    sa.Column('from_range_id', sa.Integer(), nullable=True),
    sa.Column('to_range_id', sa.Integer(), nullable=True),
    sa.Column('from_beat_id', sa.Integer(), nullable=True),
    sa.Column('to_beat_id', sa.Integer(), nullable=True),
    sa.Column('from_site_name', sa.String(length=200), nullable=True),
    sa.Column('to_site_name', sa.String(length=200), nullable=True),
    sa.Column('from_status', sa.Enum('in_stock', 'allocated', 'deployed', name='camera_status', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('in_stock', 'allocated', 'deployed', name='camera_status', native_enum=False, length=32), nullable=True),
    sa.Column('from_latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('to_latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('from_longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('to_longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('from_contact_name', sa.String(length=160), nullable=True),
    sa.Column('to_contact_name', sa.String(length=160), nullable=True),
    sa.Column('from_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('to_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_history', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_history_camera_changed', ['camera_id', 'changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_history_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_history_changed_at'), ['changed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_history_changed_at'))
        batch_op.drop_index(batch_op.f('ix_assignment_history_camera_id'))
        batch_op.drop_index('ix_assignment_history_camera_changed')

    op.drop_table('assignment_history')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_status'))
        batch_op.drop_index(batch_op.f('ix_cameras_serial_number'))
        batch_op.drop_index('ix_cameras_range_status')
        batch_op.drop_index(batch_op.f('ix_cameras_range_id'))
        batch_op.drop_index(batch_op.f('ix_cameras_beat_id'))

    op.drop_table('cameras')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beats_range_id'))

    op.drop_table('beats')
    op.drop_table('ranges')
    # ### end Alembic commands ###
